FROM solr:8.11.1

# Add the PostgreSQL JDBC driver and DIH JAR to the lib directory
ADD postgresql-42.2.24.jar /opt/solr/server/lib/
ADD solr-dataimporthandler-8.11.1.jar /opt/solr/server/solr-webapp/webapp/WEB-INF/lib/